### ISSUE TITLE
Unable to compile with Platformio

### ISSUE THREAD

**Issue by GrimorJander** [Lightwell-bg/RGB-P4-Led-Matrix-Clock-based-on-ESP32#1]
Several errors arduino.h /arduino_pins files missing.
Esp32/frame/ error...
Lightwell custom libraries not present on library finder .

Is there a project for arduino IDE users?
I just bought one of your pcb boards for esp32 and is uselles to me right now.
Thanks in advance

**Comment by GrimorJander** [comment]
Thanks @maxgerhardt, now its working OK compiling and showing in the matrix. Only thing is the webserver for android app/web configuration is not working. I was able to connect via AP and wifi provisioning to my own net. But whe trying to enter the web page of configuration, it unable to open it.

**Comment by maxgerhardt** [comment]
I think you mean [this](https://github.com/Lightwell-bg/RGB-P4-Led-Matrix-Clock-based-on-ESP32#web-interface)? I can check if I can flash it on my ESP32 without having the matrix or a OpenWeatherMap API key and see if the webserver is reachable that thing is supposed to open.

**Comment by maxgerhardt** [comment]
Since the code does reference files from the SPIFFS filesystem (https://github.com/Lightwell-bg/RGB-P4-Led-Matrix-Clock-based-on-ESP32/blob/main/Platformio/src/httpServer.h#L30-L33), did you make sure to upload the file system too? See [docs](https://docs.platformio.org/en/latest/platforms/espressif32.html#uploading-files-to-file-system), just execute the [project task](https://docs.platformio.org/en/latest/integration/ide/vscode.html#project-tasks) "Platform" -> "Upload File System image".

**Comment by GrimorJander** [comment]
> Reference

Exactly this. I can't set anything, timezone, news and weather API, youtube API... Because I can't load this web page. Either, andriñoid app and web browser get the same 404 error

**Comment by maxgerhardt** [comment]
When I add my WiFi AP in the `config.h` and do an Erase + Upload Filesystem + Upload, the ESP32 connects just fine and I get on its IP:

![grafik](https://user-images.githubusercontent.com/26485477/180840060-d194a5aa-2258-4a28-bcb2-cbe7b37e21ba.png)

**Comment by GrimorJander** [comment]
> Since the code does reference files from the SPIFFS filesystem (https://github.com/Lightwell-bg/RGB-P4-Led-Matrix-Clock-based-on-ESP32/blob/main/Platformio/src/httpServer.h#L30-L33), did you make sure to upload the file system too? See [docs](https://docs.platformio.org/en/latest/platforms/espressif32.html#uploading-files-to-file-system), just execute the [project task](https://docs.platformio.org/en/latest/integration/ide/vscode.html#project-tasks) "Platform" -> "Upload File System image".

OMG, I miss that part. Really sorry for my poor skills/impatience. Now I can connect the app. So more things solved. Thank Maximilian.
